# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14Xwm-TfYGlVypEtC4nP8SukLLRCXRrZ_
"""



"""# intro

"""

